### ISSUE TITLE
metropolis_hasting_producer_10 fails

### ISSUE THREAD

**Issue by bangerth** [bangerth/SampleFlow#111]
@dawsoneliasen -- the `metropolis_hasting_producer_10` fails on my system, because it generates 10 samples but the stored output file has 20 lines (or the other way around). Can you come up with a pull request that fixes this and for which you can confirm that when you run `ctest` that all tests succeed? Thanks!

**Comment by dawsoneliasen** [comment]
@bangerth sorry about that, I know what went wrong and I can introduce a PR that fixes it but I'm currently unable to run `ctest` on my machine since doxygen is now required. I'm having trouble installing it due to an issue with my package manager. I tried building it from source but I still get an error from `cmake .` telling me that doxygen could not be found.

**Comment by dawsoneliasen** [comment]
@bangerth I was able to get around the installation issues by modifying my `$PATH`. The change proposed in #112 passes all tests.
